#!/usr/bin/python
import csv, json, os, random, re, sys, time, redis, tweepy, getpass
import configparser
from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search
import ssl
from elasticsearch.connection import create_ssl_context

try:
        ssl_context = create_ssl_context(cafile='/home/root-ca.pem')
        ssl_context.check_hostname = False
        ssl_context.verify_mode = ssl.CERT_NONE

        client = Elasticsearch('https://hp0.netwarsystem.com:9200', ssl_context=ssl_context, timeout=60, http_auth=("admin", "admin"))
except:
        sys.exit()

#867786088969940994
#response = client.search(
#    index="tumaster",
#    body={
# 	 "query": {
#    		"regexp": {
#      	"screen_name": "[a-zA-Z]{4,8}[0-9]{4,8}"
#    }
#  }
#}
#)


for hit in response['hits']['hits']:
	print(str(hit) + "\n")

#s = Search(using=client, index="tumaster").query("match", text=sys.argv[1])
#response = s.execute()
#print(dir(response))
#print(response)
#print(dir(response[0]))
#for resp in response:
#	print(resp.user['screen_name'])
#	print(resp.text)
##print(response[0].text)
