#!/usr/bin/python
import csv, json, os, random, re, sys, time, redis, tweepy, getpass
import configparser
from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search
import ssl
from elasticsearch.connection import create_ssl_context

try:
        ssl_context = create_ssl_context(cafile='/home/root-ca.pem')
        ssl_context.check_hostname = False
        ssl_context.verify_mode = ssl.CERT_NONE

        client = Elasticsearch('https://hp0.netwarsystem.com:9200', ssl_context=ssl_context, timeout=60, http_auth=("admin", "admin"))
except:
        sys.exit()


s = Search(using=client, index="tumaster").query("match", _id=sys.argv[1])
response = s.execute()
if(response):
	k = 0
else:
	print(sys.argv[1])
#for hit in s.scan():
#	print(hit)
