#!/usr/bin/python
import csv, json, os, random, re, sys, time, redis, tweepy, getpass
import configparser
from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search
import ssl
from elasticsearch.connection import create_ssl_context

#config = simpleconfigparser()
#config.read(os.environ['HOME'] +'/.twitter')

#auth = tweepy.OAuthHandler(config[API][consumer_key], config[API][consumer_secret])
#auth.set_access_token(config[API][access_token_key], config[API][access_token_secret])
#api = tweepy.API(auth)
#my = api.verify_credentials()


try:
        ssl_context = create_ssl_context(cafile='/home/root-ca.pem')
        ssl_context.check_hostname = False
        ssl_context.verify_mode = ssl.CERT_NONE

        client = Elasticsearch('https://hp0.netwarsystem.com:9200', ssl_context=ssl_context, timeout=60, http_auth=("admin", "LongPassword2019"))
except:
        sys.exit()


s = Search(using=client, index="tumaster").query("match", text=sys.argv[1])
response = s.execute()
print(dir(response))
print(response)
#print(dir(response[0]))
for resp in response:
	print(resp.user['screen_name'])
	print(resp.text)
#print(response[0].text)
