#!/usr/bin/python
#DESC: print  members of <USER'S> <LIST>
import tweepy, redis
import csv, json, sys, os
from simpleconfigparser import simpleconfigparser
from time import gmtime, strftime

config = simpleconfigparser()
config.read(os.environ['HOME'] +'/.twitter')

r = redis.StrictRedis(host='localhost', port=6379, db=0)

auth = tweepy.OAuthHandler(config.API.consumer_key, config.API.consumer_secret)
auth.set_access_token(config.API.access_token_key, config.API.access_token_secret)
api = tweepy.API(auth)

y = api.verify_credentials()
name = y.screen_name

if len(sys.argv) == 2:
    targlist = sys.argv[1]
if len(sys.argv) == 3:
    name = sys.argv[1]
    targlist = sys.argv[2]

for member in tweepy.Cursor(api.list_members, name, targlist).items():
    if True:
        try:
            y = r.get(member.screen_name)
            if y:
                # given an ID number
                if(len(y)) > 19:
                    print(y)
                else:
                # given a text name, dig deeper
                    print(r.get(y))
                sys.exit()
        except (RuntimeError, TypeError, NameError):
                pass

    if True:
        try:
            z = api.get_user(member.screen_name)
            if z:
                # save name, number pair
                r.set(member.screen_name,z.id_str)
                # save number, full json
                r.set(z.id_str,json.dumps(z._json))
                print(member.screen_name + " " + z.id_str)
                #print(json.dumps(z._json))
        except (RuntimeError, TypeError, NameError):
            pass
