#!/usr/bin/python
#GET lists/list			15	15
#GET lists/members		180	15
#GET lists/members/show		15	15
#GET lists/memberships		15	15
#GET lists/ownerships		15	15
#GET lists/show			15	15
#GET lists/statuses		180	180
#GET lists/subscribers		180	15
#GET lists/subscribers/show	15	15
#GET lists/subscriptions	15	15
import tweepy, os
from simpleconfigparser import simpleconfigparser

config = simpleconfigparser()
config.read(os.environ['HOME'] +'/.twitter')

auth = tweepy.OAuthHandler(config.API.consumer_key, config.API.consumer_secret)
auth.set_access_token(config.API.access_token_key, config.API.access_token_secret)
api = tweepy.API(auth)

#rlim = api.rate_limit_status()[u'resources'][u'statuses'][u'/statuses/user_timeline'][u'remaining']

#for thing in api.rate_limit_status()[u'resources'][u'favorites']:
for thing1 in api.rate_limit_status()[u'resources']:
	#print(thing1)
        for thing2 in api.rate_limit_status()[u'resources'][thing1]:
		print(thing2)
                print(api.rate_limit_status()[u'resources'][thing1][thing2][u'limit'])
                print(api.rate_limit_status()[u'resources'][thing1][thing2][u'remaining'])

