#!/usr/bin/python
import csv, json, os, random, re, sys, time, redis, tweepy, getpass
import configparser
from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search
import ssl
from elasticsearch.connection import create_ssl_context
import squish2, requests

#urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
requests.packages.urllib3.disable_warnings()

sysconf = configparser.ConfigParser()
sysconf.read('/etc/netwar/netwar.conf')

if(sysconf['SYSTEM']['elksg'][:5] == "https"):
	try:
		ssl_context = create_ssl_context(cafile='/home/root-ca.pem')
		ssl_context.check_hostname = False
		ssl_context.verify_mode = ssl.CERT_NONE
		client = Elasticsearch(sysconf['SYSTEM']['elksg'], ssl_context=ssl_context, timeout=60, http_auth=(sysconf['SYSTEM']['elksguser'], sysconf['SYSTEM']['elksgpass']))
	except:
		sys.exit()
else:
	client = Elasticsearch(sysconf['SYSTEM']['elksg'])

if(len(sys.argv) < 3):
        print("tw-1name <index> <screen_name>")
        sys.exit()

s = Search(using=client, index=sys.argv[1]).query("match",screen_name=sys.argv[2])
response = s.execute()
if(response):
	for resp in response:
		print(resp['screen_name'] + " " + resp['id_str'])
else:
	print(sys.argv[1] + " not found")
