#!/usr/bin/python
#DESC: Save screen name, ID, some other stats for a screen name.
import tweepy
import os, sys, json
from simpleconfigparser import simpleconfigparser
from time import gmtime, strftime
from elasticsearch import Elasticsearch

config = simpleconfigparser()
config.read(os.environ['HOME'] +'/.twitter')


auth = tweepy.OAuthHandler(config.API.consumer_key, config.API.consumer_secret)
auth.set_access_token(config.API.access_token_key, config.API.access_token_secret)
api = tweepy.API(auth)


try:
	client = Elasticsearch()
except:
	print("no client")
	sys.exit()

cnt = 1
if True:
	try:
		for page in tweepy.Cursor(api.followers_ids, screen_name=sys.argv[1]).pages():
			bod = ""
			for derp in page:
				print(cnt)
				cnt = cnt + 1
				z = api.get_user(id=derp)
				bod = "{ \"index\" : { \"_index\" : \"twusers\", \"_type\" : \"twuser\" } }\n"
				bod = bod + json.dumps(z._json) + "\n"
		k = client.bulk(index="twusers",doc_type="twuser",body=bod)
	except (RuntimeError, TypeError, NameError):
		pass
