#!/usr/bin/python
#GET lists/list			15	15
#GET lists/members		180	15
#GET lists/members/show		15	15
#GET lists/memberships		15	15
#GET lists/ownerships		15	15
#GET lists/show			15	15
#GET lists/statuses		180	180
#GET lists/subscribers		180	15
#GET lists/subscribers/show	15	15
#GET lists/subscriptions	15	15
import tweepy, os
import configparser

config = configparser()
config.read(os.environ['HOME'] +'/.twitter')

auth = tweepy.OAuthHandler(config[API][consumer_key], config[API][consumer_secret])
auth.set_access_token(config[API][access_token_key], config[API][access_token_secret])
api = tweepy.API(auth)

#rlim = api.rate_limit_status()[u'resources'][u'statuses'][u'/statuses/user_timeline'][u'remaining']

print "lists/subscribers/show " + str(api.rate_limit_status()[u'resources'][u'lists'][u'/lists/subscribers/show'][u'remaining'])
print "lists/subscriptions " + str(api.rate_limit_status()[u'resources'][u'lists'][u'/lists/subscriptions'][u'remaining'])
print "lists/statuses " + str(api.rate_limit_status()[u'resources'][u'lists'][u'/lists/statuses'][u'remaining'])
print "lists/members/show " + str(api.rate_limit_status()[u'resources'][u'lists'][u'/lists/members/show'][u'remaining'])
print "lists/subscribers " + str(api.rate_limit_status()[u'resources'][u'lists'][u'/lists/subscribers'][u'remaining'])
print "lists/lists " + str(api.rate_limit_status()[u'resources'][u'lists'][u'/lists/list'][u'remaining'])
print "lists/show " + str(api.rate_limit_status()[u'resources'][u'lists'][u'/lists/show'][u'remaining'])
print "lists/memberships " + str(api.rate_limit_status()[u'resources'][u'lists'][u'/lists/memberships'][u'remaining'])
print "lists/members " + str(api.rate_limit_status()[u'resources'][u'lists'][u'/lists/members'][u'remaining'])
print "lists/ownerships " + str(api.rate_limit_status()[u'resources'][u'lists'][u'/lists/ownerships']['remaining'])
