#!/usr/bin/python
import urllib2,sys,tweepy,os,re
from simpleconfigparser import simpleconfigparser
from bs4 import BeautifulSoup

name = re.sub("idle-", "",sys.argv[1])

#Account does not exist, or account has self-suspended, no way to tell w/o
#trying to rename another account into the name in question
try:
    urllib2.urlopen("http://twitter.com/" + name)
except urllib2.URLError:
    print(name + " renamed")
    exit(1)

#Account has been suspended by Twitter - this misses some jihadi accounts maybe UTF-8 again?
soup = BeautifulSoup(urllib2.urlopen("http://twitter.com/" + name), "html5lib")
for thing in soup("title"):
    if(thing.text == "Twitter / Account Suspended"):
        print(name + " suspended")
        exit(2)

config = simpleconfigparser()
config.read(os.environ['HOME'] +'/.twitter')

auth = tweepy.OAuthHandler(config.API.consumer_key, config.API.consumer_secret)
auth.set_access_token(config.API.access_token_key, config.API.access_token_secret)
api = tweepy.API(auth)

#This is the account lookup that gets overloaded, leading to spurious idling
lookups = api.rate_limit_status()[u'resources'][u'users'][u'/users/show/:id'][u'remaining']
if (lookups < 10):
    print("API exhausted")
    exit(3)

#Account is protected, friendship checks in tweepy just don't work
#so try to get one tweet to see if we are following the target
y = api.get_user(name)
if y.protected:
    try:
        cnt = len(api.user_timeline(screen_name = name,count=1))
    except tweepy.TweepError:
        print(name + " protected")
        exit(4)
cnt = len(api.user_timeline(screen_name = name,count=1))
if(cnt == 0):
   print(name + " empty")
   exit(5)
print(name + " accessible")
exit(0)
