#!/usr/bin/python
import csv, json, os, random, re, sys, time, redis, tweepy, getpass
import configparser
from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search
import ssl
from elasticsearch.connection import create_ssl_context
import squish2, requests

#urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
requests.packages.urllib3.disable_warnings()

config = configparser.ConfigParser()
config.read(os.environ['HOME'] +'/.twitter')
sysconf = configparser.ConfigParser()
sysconf.read('/etc/netwar/netwar.conf')

if(sysconf['SYSTEM']['elksg'][:5] == "https"):
	try:
		ssl_context = create_ssl_context(cafile='/home/root-ca.pem')
		ssl_context.check_hostname = False
		ssl_context.verify_mode = ssl.CERT_NONE
		client = Elasticsearch(sysconf['SYSTEM']['elksg'], ssl_context=ssl_context, timeout=60, http_auth=(sysconf['SYSTEM']['elksguser'], sysconf['SYSTEM']['elksgpass']))
	except:
		sys.exit()
else:
	client = Elasticsearch(sysconf['SYSTEM']['elksg'])

found = open(sys.argv[2] + "-found.txt", 'w')
missd = open(sys.argv[2] + "-missed.txt", 'w')
accts = open(sys.argv[2], 'r')
for acct in accts:
	acct = acct.rstrip()
	s = Search(using=client, index=sys.argv[1]).query("match",screen_name=acct)
	response = s.execute()
	if(response):
		for resp in response:
			print(resp['id_str'])
			found.write(resp['id_str'] + "\n")
	else:
		print(acct)
		missd.write(str(acct) + "\n")
