#!/usr/bin/python
#DESC: show name of account /w credentials in ~/.twitter 
import tweepy
import os, sys
import botornot
from simpleconfigparser import simpleconfigparser

config = simpleconfigparser()
config.read(os.environ['HOME'] +'/.twitter')

twitter_app_auth = {
    'consumer_key': config.API.consumer_key,
    'consumer_secret': config.API.consumer_secret,
    'access_token': config.API.access_token_key,
    'access_token_secret': config.API.access_token_secret,
  }
bon = botornot.BotOrNot(**twitter_app_auth)

result = bon.check_account(sys.argv[1])
print result
