#!/bin/bash
#DESC: This is invoked by N-queue only IN the target directory
#Is there ever a use case for this? NRR 2015-04-16
DERP=`date +%Y-%m-%d-%H-%M`
echo $DERP
export HOMEDIR=`tw-home`
export FULLPATH="$HOME/$HOMEDIR/"

echo "awakening accounts"
ls idle-* | awk -F "idle-" {'print "mv " $0 " " $2'} > movethem
sh movethem
rm movethem
