#!/usr/bin/python
#DESC: show name of account /w credentials in ~/.twitter 
import tweepy
import os, sys
import botometer
from simpleconfigparser import simpleconfigparser

config = simpleconfigparser()
config.read(os.environ['HOME'] +'/.twitter')

twitter_app_auth = {
    'consumer_key': config.API.consumer_key,
    'consumer_secret': config.API.consumer_secret,
    'access_token': config.API.access_token_key,
    'access_token_secret': config.API.access_token_secret,
  }
bon = botornot.BotOrNot(**twitter_app_auth)

result = bon.check_account(sys.argv[1])
print result


#import botometer
#
#mashape_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
#twitter_app_auth = {
#    'consumer_key': 'xxxxxxxx',
#    'consumer_secret': 'xxxxxxxxxx',
#    'access_token': 'xxxxxxxxx',
#    'access_token_secret': 'xxxxxxxxxxx',
#  }
#bom = botometer.Botometer(wait_on_ratelimit=True,
#                          mashape_key=mashape_key,
#                          **twitter_app_auth)
#
## Check a single account by screen name
#result = bom.check_account('@clayadavis')
#
## Check a single account by id
#result = bom.check_account(1548959833)
#
## Check a sequence of accounts
#accounts = ['@clayadavis', '@onurvarol', '@jabawack']
#for screen_name, result in bom.check_accounts_in(accounts):
#    # Do stuff with `screen_name` and `result`
