#!/bin/bash
while [ 1 ]
do
    clear
    ps aux | grep "stream" | grep "tw-[2-9]neo" | sort | awk -F " " {'print $1 " " $12 " " $13 " " $14'}
    echo
    ps aux | grep "stream" | grep "tw-usersearchadd" | sort | awk -F " " {'print $1 " " $12 " " $13 " " $14'}
    echo
    ps aux | grep "stream" | grep "quick" | sort | awk -F " " {'print $1 " " $12 " " $13 " " $14'}
    ps aux | grep "stream" | awk '/tw-followq / || /tw-friendq /' | sort | awk -F " " {'print $1 " " $12 " " $13 " " $14'}

    echo
    ps aux | grep "stream" | grep "2gml" | sort | awk -F " " {'print $1 " " $12 " " $13 " " $14'}
    echo
    elg usert | awk {'print $7'}
    tw-showwork usertest
    tw-showwork trickle
    tw-showwork friends
    tw-showwork follows
    zoot
done
    
