#!/bin/bash
while [ 1 ]
do
    clear
    ps aux | grep "stream[0-9]" | grep "tw-catchstream" | sort | awk -F " " {'print $1 " " $13 '} | sed 's/\/usr\/local\/bin\///' | column
    echo

    tw-walshow $1
    wait15
done
    
