#!/bin/bash
while [ 1 ]
do
    clear
    ps aux | grep "stream" | grep "tw-catchstream" | sort | awk -F " " {'print $1 " " $12 " " $13 " " $14'} | sed 's/\/usr\/local\/bin\///' | column
    echo

    tw-walshow $1
    zoot
done
    
