#!/usr/bin/python
import csv, json, os, random, re, sys, time, redis, tweepy, getpass, re, math
import configparser
from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search
import ssl, requests
from elasticsearch.connection import create_ssl_context
import networkx as nx
from scipy.stats.mstats import gmean
from textblob import TextBlob
#urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
requests.packages.urllib3.disable_warnings()


config = configparser.ConfigParser()
config.read(os.environ['HOME'] +'/.twitter')

if(config['STREAM']['elksg'][:5] == "https"):
	try:
		ssl_context = create_ssl_context(cafile='/home/root-ca.pem')
		ssl_context.check_hostname = False
		ssl_context.verify_mode = ssl.CERT_NONE
		client = Elasticsearch(config['STREAM']['elksg'], ssl_context=ssl_context, timeout=60, http_auth=(config['STREAM']['elksguser'], config['STREAM']['elksgpass']))
	except:
		sys.exit()
else:
	client = Elasticsearch(config['STREAM']['elksg'])

names = open(sys.argv[1],'r')
DG = nx.DiGraph()

for file in names:
	fname = re.sub(".txt", "",file.rstrip())
	s = Search(using=client, index="usertest").query("match",screen_name=fname)
	response = s.execute()
	if(response):
		for resp in response:
			print("foo")
	accts = open(fname + ".txt", 'r')
	for line in accts:
		s = Search(using=client, index="usertest").query("match",id_str=line)
		response = s.execute()
		if(response):
			for resp in response:
				print(dir(resp))
				print("too!")
				print(resp['description'])
				blob = TextBlob(resp['description'])
				print(blob.tags)
				print(blob.noun_phrases)
				for sentence in blob.sentences:
					print(sentence.sentiment.polarity)

