#!/usr/bin/python
#DESC: print followers for a given screenname.
import tweepy, os, sys, time
import configparser

config = configparser.ConfigParser()
config.read(os.environ['HOME'] +'/.twitter')

auth = tweepy.OAuthHandler(config['API']['consumer_key'], config['API']['consumer_secret'])
auth.set_access_token(config['API']['access_token_key'], config['API']['access_token_secret'])
api = tweepy.API(auth)

y = api.get_user(sys.argv[1])
derps = api.followers_ids(sys.argv[1])
#print(type(derps))
derps.sort()
for derp in derps:
    print(str(y.id_str) + "," + str(derp))
#    all = api.rate_limit_status()[u'resources'][u'followers'][u'/followers/ids'][u'remaining']
#    print all
#    try:
#        name = api.get_user(derp).screen_name
#        print name 
#    except (RuntimeError, TypeError, NameError):
#        pass
