#!/usr/bin/python
#DESC: print URLs for an account's favorited tweets.
import tweepy, csv, sys, os
import configparser

config = configparser()
config.read(os.environ['HOME'] +'/.twitter')

auth = tweepy.OAuthHandler(config[API][consumer_key], config[API][consumer_secret])
auth.set_access_token(config[API][access_token_key], config[API][access_token_secret])
api = tweepy.API(auth)

name = config[API].account
last = ""

if len(sys.argv) > 1:
   name = sys.argv[1]
# second parm is the most recent favorite
if len(sys.argv) > 2:
   last = sys.argv[2]

#how do we check case?

#for member in tweepy.Cursor(api.list_members,name,list.slug).items():
#faves  = api.favorites(name)
for fave in tweepy.Cursor(api.favorites,name).items():
    if fave.id_str == last:
        sys.exit()
    print name + "," + fave.author.screen_name
