#!/usr/bin/python
import csv, json, os, random, re, sys, time, redis, tweepy, getpass, re
import configparser
from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search
import ssl, requests
from elasticsearch.connection import create_ssl_context
#urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
requests.packages.urllib3.disable_warnings()


config = configparser.ConfigParser()
config.read(os.environ['HOME'] +'/.twitter')
sysconf = configparser.ConfigParser()
sysconf.read('/etc/netwar/netwar.conf')

if(config['SYSTEM']['elksg'][:5] == "https"):
	try:
		ssl_context = create_ssl_context(cafile='/home/root-ca.pem')
		ssl_context.check_hostname = False
		ssl_context.verify_mode = ssl.CERT_NONE
		client = Elasticsearch(config['SYSTEM']['elksg'], ssl_context=ssl_context, timeout=60, http_auth=(config['SYSTEM']['elksguser'], config['SYSTEM']['elksgpass']))
	except:
		sys.exit()
else:
	client = Elasticsearch(config['SYSTEM']['elksg'])

fname = re.sub(".txt", "",sys.argv[1])

accts = open(fname + ".txt", 'r')
out = open(fname + ".ggg", 'w')
for line in accts:
	s = Search(using=client, index="usertest").query("match",id_str=line)
	response = s.execute()
	if(response):
		for resp in response:
			print(fname + "," + resp['screen_name'])
			out.write(fname + "," + resp['screen_name'] + "\n")

