#!/usr/bin/python
import configparser, sys
import graphistry
import pandas as pd

sysconf = configparser.ConfigParser()
sysconf.read('/etc/netwar/netwar.conf')

graphistry.register(key=sysconf['SYSTEM']['graphistry'])

links = pd.read_csv(sys.argv[1])
plotter = graphistry.bind(source="src", destination="dst")
plotter.plot(links)
