#!/usr/bin/python
# twitter account dispatcher
import csv, json, os, random, re, sys, time, hashlib
import redis
from walrus import *

wal = Walrus(host='localhost', port=6379, db=0)
q0 = wal.Set("0queuework")
q1 = wal.Set("1queuework")
q2 = wal.Set("2queuework")
q3 = wal.Set("3queuework")
q4 = wal.Set("4queuework")
q5 = wal.Set("5queuework")
q6 = wal.Set("6queuework")
q7 = wal.Set("7queuework")
q8 = wal.Set("8queuework")
q9 = wal.Set("9queuework")
qa = wal.Set("aqueuework")
qb = wal.Set("bqueuework")
qc = wal.Set("cqueuework")
qd = wal.Set("dqueuework")
qe = wal.Set("equeuework")
qf = wal.Set("fqueuework")

accts = open(sys.argv[1], 'r')

for acct in accts:
	acct = acct.rstrip()
	qq = hashlib.md5(acct).hexdigest()[5]
	print(qq + " " + acct)
        if(qq == "0"):
		q0.add(acct)
        if(qq == "1"):
		q1.add(acct)
        if(qq == "2"):
		q2.add(acct)
        if(qq == "3"):
		q3.add(acct)
        if(qq == "4"):
		q4.add(acct)
        if(qq == "5"):
		q5.add(acct)
        if(qq == "6"):
		q6.add(acct)
        if(qq == "7"):
		q7.add(acct)
        if(qq == "8"):
		q8.add(acct)
        if(qq == "9"):
		q9.add(acct)
        if(qq == "a"):
		qa.add(acct)
        if(qq == "b"):
		qb.add(acct)
        if(qq == "c"):
		qc.add(acct)
        if(qq == "d"):
		qd.add(acct)
        if(qq == "e"):
		qe.add(acct)
        if(qq == "f"):
		qf.add(acct)

