#!/usr/bin/python
# twitter account dispatcher
import csv, json, os, random, re, sys, time, hashlib
import redis
from walrus import *

wal = Walrus(host='localhost', port=6379, db=0)
q0 = wal.Set("queue10work")
q1 = wal.Set("queue11work")
q2 = wal.Set("queue12work")
q3 = wal.Set("queue13work")
q4 = wal.Set("queue14work")
q5 = wal.Set("queue15work")
q6 = wal.Set("queue16work")
q7 = wal.Set("queue17work")
q8 = wal.Set("queue18work")
q9 = wal.Set("queue19work")
qa = wal.Set("queue1awork")
qb = wal.Set("queue1bwork")
qc = wal.Set("queue1cwork")
qd = wal.Set("queue1dwork")
qe = wal.Set("queue1ework")
qf = wal.Set("queue1fwork")

accts = open(sys.argv[1], 'r')

for acct in accts:
	acct = acct.rstrip()
	qq = hashlib.md5(acct.encode("utf-8")).hexdigest()[5]
	print(qq + " " + acct)
	if(qq == "0"):
		q0.add(acct)
	if(qq == "1"):
		q1.add(acct)
	if(qq == "2"):
		q2.add(acct)
	if(qq == "3"):
		q3.add(acct)
	if(qq == "4"):
		q4.add(acct)
	if(qq == "5"):
		q5.add(acct)
	if(qq == "6"):
		q6.add(acct)
	if(qq == "7"):
		q7.add(acct)
	if(qq == "8"):
		q8.add(acct)
	if(qq == "9"):
		q9.add(acct)
	if(qq == "a"):
		qa.add(acct)
	if(qq == "b"):
		qb.add(acct)
	if(qq == "c"):
		qc.add(acct)
	if(qq == "d"):
		qd.add(acct)
	if(qq == "e"):
		qe.add(acct)
	if(qq == "f"):
		qf.add(acct)
