#!/usr/bin/python
# twitter account dispatcher
import csv, json, os, random, re, sys, time, hashlib
import redis
from walrus import *

wal = Walrus(host='localhost', port=6379, db=0)
q0 = wal.Set("queue0work")
q1 = wal.Set("queue1work")
q2 = wal.Set("queue2work")
q3 = wal.Set("queue3work")
q4 = wal.Set("queue4work")
q5 = wal.Set("queue5work")
q6 = wal.Set("queue6work")
q7 = wal.Set("queue7work")
q8 = wal.Set("queue8work")
q9 = wal.Set("queue9work")
qa = wal.Set("queueawork")
qb = wal.Set("queuebwork")
qc = wal.Set("queuecwork")
qd = wal.Set("queuedwork")
qe = wal.Set("queueework")
qf = wal.Set("queuefwork")

accts = open(sys.argv[1], 'r')

for acct in accts:
	acct = acct.rstrip()
	qq = hashlib.md5(acct).hexdigest()[5]
	print(qq + " " + acct)
        if(qq == "0"):
		q0.add(acct)
        if(qq == "1"):
		q1.add(acct)
        if(qq == "2"):
		q2.add(acct)
        if(qq == "3"):
		q3.add(acct)
        if(qq == "4"):
		q4.add(acct)
        if(qq == "5"):
		q5.add(acct)
        if(qq == "6"):
		q6.add(acct)
        if(qq == "7"):
		q7.add(acct)
        if(qq == "8"):
		q8.add(acct)
        if(qq == "9"):
		q9.add(acct)
        if(qq == "a"):
		qa.add(acct)
        if(qq == "b"):
		qb.add(acct)
        if(qq == "c"):
		qc.add(acct)
        if(qq == "d"):
		qd.add(acct)
        if(qq == "e"):
		qe.add(acct)
        if(qq == "f"):
		qf.add(acct)

