#!/usr/bin/python
# twitter account dispatcher
import csv, json, os, random, re, sys, time, hashlib
import redis
from walrus import *

wal = Walrus(host='localhost', port=6379, db=0)
q0 = wal.Set("queue20work")
q1 = wal.Set("queue21work")
q2 = wal.Set("queue22work")
q3 = wal.Set("queue23work")
q4 = wal.Set("queue24work")
q5 = wal.Set("queue25work")
q6 = wal.Set("queue26work")
q7 = wal.Set("queue27work")
q8 = wal.Set("queue28work")
q9 = wal.Set("queue29work")
qa = wal.Set("queue2awork")
qb = wal.Set("queue2bwork")
qc = wal.Set("queue2cwork")
qd = wal.Set("queue2dwork")
qe = wal.Set("queue2ework")
qf = wal.Set("queue2fwork")

accts = open(sys.argv[1], 'r')

for acct in accts:
	acct = acct.rstrip()
	qq = hashlib.md5(acct.encode("utf-8")).hexdigest()[5]
	print(qq + " " + acct)
	if(qq == "0"):
		q0.add(acct)
	if(qq == "1"):
		q1.add(acct)
	if(qq == "2"):
		q2.add(acct)
	if(qq == "3"):
		q3.add(acct)
	if(qq == "4"):
		q4.add(acct)
	if(qq == "5"):
		q5.add(acct)
	if(qq == "6"):
		q6.add(acct)
	if(qq == "7"):
		q7.add(acct)
	if(qq == "8"):
		q8.add(acct)
	if(qq == "9"):
		q9.add(acct)
	if(qq == "a"):
		qa.add(acct)
	if(qq == "b"):
		qb.add(acct)
	if(qq == "c"):
		qc.add(acct)
	if(qq == "d"):
		qd.add(acct)
	if(qq == "e"):
		qe.add(acct)
	if(qq == "f"):
		qf.add(acct)
