#!/usr/bin/python
# one shot bulk Twitter account recorder
import csv, json, os, random, re, sys, time, datetime
import configparser
from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search
import ssl
from elasticsearch.connection import create_ssl_context
import requests

requests.packages.urllib3.disable_warnings()


config = configparser.ConfigParser()
config.read(os.environ['HOME'] +'/.twitter')

if(config['SYSTEM']['elksg'][:5] == "https"):
	try:
		ssl_context = create_ssl_context(cafile='/home/root-ca.pem')
		ssl_context.check_hostname = False
		ssl_context.verify_mode = ssl.CERT_NONE
		client = Elasticsearch(config['SYSTEM']['elksg'], ssl_context=ssl_context, timeout=60, http_auth=(config['SYSTEM']['elksguser'], config['SYSTEM']['elksgpass']))
	except:
		sys.exit()
else:
	client = Elasticsearch(config['SYSTEM']['elksg'])

tweets = open(sys.argv[1], 'r')
twbod = ""
cnt = 0
for line in tweets:
	twbod = twbod + "{ \"index\" : { \"_index\" : \"indexname\", \"_type\" : \"tweets\"} }\n"
	twbod = twbod + line
	cnt = cnt + 1
	if(cnt > 199):
		client.bulk(index="tu" + sys.argv[1],doc_type="userid",body=twbod)
		cnt = 0
