#!/usr/bin/python
# twitter account dispatcher
import csv, json, os, random, re, sys, time, hashlib
import redis, configparser
from walrus import *

config = configparser.ConfigParser()
config.read(os.environ['HOME'] +'/.twitter')

wal = Walrus(host=config['STREAM']['redishost'],port=config['STREAM']['redisport'], db=0)
qq = wal.Set("friends")

accts = open(sys.argv[1], 'r')

for acct in accts:
	acct = str(acct.rstrip())
	qq.add(acct)
