#!/usr/bin/env python
# encoding: utf-8
#DESC: download tweets from a given screen name
#DATE: 12/25/2015
import tweepy, csv, sys, os, re
from time import gmtime, strftime
import configparser

config = configparser.ConfigParser()
config.read(os.environ['HOME'] +'/.twitter')
 
def get_all_tweets(screen_name,thelast):
        auth = tweepy.OAuthHandler(config['API']['consumer_key'], config['API']['consumer_secret'])
        auth.set_access_token(config['API']['access_token_key'], config['API']['access_token_secret'])
        api = tweepy.API(auth)
        y = api.get_user(screen_name)
        #initialize a list to hold all the tweepy Tweets
        alltweets = []        
        
        new_tweets = api.user_timeline(screen_name = screen_name,count=20)
        
        found = 0
        for tweet in new_tweets:
            if str(tweet.id) == thelast:
              found = 1
        alltweets.extend(new_tweets)
        oldest = alltweets[-1].id - 1
        while len(new_tweets) > 0 and found < 1:
                new_tweets = api.user_timeline(screen_name = screen_name,count=200,max_id=oldest)
                for tweet in new_tweets:
                   if str(tweet.id) == thelast:
                       found = 1
                alltweets.extend(new_tweets)
                oldest = alltweets[-1].id - 1

        um = open(sys.argv[1] + "-mentions",'w')
        tw = open(sys.argv[1],'w')        
        for tweet in alltweets:
            if str(tweet.id) == thelast:
               tw.close()
               um.close()
               sys.exit()
            s = tweet.text.encode('utf-8')
            s = s.replace('\n', ' ')
            devtype = tweet.source.replace(' ', '')
            tw.write(str(tweet.id) + " " + str(tweet.created_at) + " UTC <" + user + "> " + s +" source::" + devtype.encode('utf-8') +  "\n")
            for forp in tweet.entities['user_mentions']:
                um.write(sys.argv[1] + "," + forp['screen_name'] + "," + str(tweet.created_at) + "\n")

        pass
 
 
if __name__ == '__main__':
    user = sys.argv[1]
    last = "999999999999999999"
    if len(sys.argv) > 2:
        last = sys.argv[2]
    print("Last tweet was: " + last + "\n")
    get_all_tweets(user,last)
