#!/usr/bin/python
# example of creating a single line to bulk load data to Elastic
from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search
import sys, time

client = Elasticsearch()


f = open(sys.argv[1], 'r')
order = "{ \"index\" : { \"_index\" : \"small\", \"_type\" : \"tweets\" }\n"
bod = ""
count = 0
for line in f:
	bod = bod + order
	bod = bod + line
	count = count + 1
	if(count > 200):
		try:
			client.bulk(index="small",doc_type="tweets",body=bod)
		except (RuntimeError, TypeError, NameError):
			pass
		bod = ""
		count = 0
