#!/usr/bin/python
#
# This is used to turn a file of numeric IDs representing an account's
# followers into a csv containing the text name of follower and the
# target account. Should have a followers/friends option to reverse
# them, but doesn't exist yet.
#
import csv, json, os, random, re, sys, time, redis, tweepy, getpass, re
import configparser
from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search
import ssl, requests
from elasticsearch.connection import create_ssl_context
#urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
requests.packages.urllib3.disable_warnings()


config = configparser.ConfigParser()
config.read(os.environ['HOME'] +'/.twitter')
sysconf = configparser.ConfigParser()
sysconf.read('/etc/netwar/netwar.conf')

if(sysconf['SYSTEM']['elksg'][:5] == "https"):
	try:
		ssl_context = create_ssl_context(cafile='/home/root-ca.pem')
		ssl_context.check_hostname = False
		ssl_context.verify_mode = ssl.CERT_NONE
		client = Elasticsearch(sysconf['SYSTEM']['elksg'], ssl_context=ssl_context, timeout=60, http_auth=(sysconf['SYSTEM']['elksguser'], sysconf['SYSTEM']['elksgpass']))
	except:
		sys.exit()
else:
	client = Elasticsearch(sysconf['SYSTEM']['elksg'])

fname = re.sub(".txt", "",sys.argv[2])
accts = open(fname + ".txt", 'r')
out = open(fname + ".csv", 'w')

for line in accts:
	acct = line.strip()
	s = Search(using=client, index=sys.argv[1]).query("match",id_str=acct)
	response = s.execute()
	if(response):
		for resp in response:
			print(resp['screen_name'] + "," + fname)
			out.write(resp['screen_name'] + "," + fname + "\n")

