#!/usr/bin/python
import sys
from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search
from elasticsearch_dsl import Q
from addict import Dict

f = open(sys.argv[2],'r')

items = []
for line in f:
	zoo = Dict()
	zoo[sys.argv[1]] = line.rstrip()
	l = Dict()
	l.match_phrase = zoo
	items.append(l)

		
w = Dict()
w.bool.should = items
w.bool.minimum_should_match = 1
print(w.to_dict())
