#!/usr/bin/python
import sys
from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search
from elasticsearch_dsl import Q
from addict import Dict
import squish2

q = Q(squish2.mkfilter(sys.argv[1], sys.argv[2]))
print("{ \"query\": " + str(q.to_dict()) + "}")
