#!/usr/bin/python
#DESC: print followers for a given screenname.
import tweepy, os, sys, time
import configparser

config = configparser()
config.read(os.environ['HOME'] +'/.twitter')


auth = tweepy.OAuthHandler(config[API][consumer_key], config[API][consumer_secret])
auth.set_access_token(config[API][access_token_key], config[API][access_token_secret])
api = tweepy.API(auth)

derps = api.followers_ids(sys.argv[1])
for derp in derps:
    try:
        name = api.get_user(derp).screen_name
        print name 
    except (RuntimeError, TypeError, NameError):
        pass
#used to sleep, now used for quick results on small accounts
#    time.sleep(6)
