#!/usr/bin/python
import os, sys, json, time, psutil, setproctitle, datetime
import configparser, getpass, platform
from elasticsearch import Elasticsearch
import ssl, requests
from elasticsearch.connection import create_ssl_context
import squish2, requests
#urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
requests.packages.urllib3.disable_warnings()

config = configparser.ConfigParser()
config.read(os.environ['HOME'] +'/.twitter')

if(config['SYSTEM']['elksg'][:5] == "https"):
	try:
		ssl_context = create_ssl_context(cafile='/home/root-ca.pem')
		ssl_context.check_hostname = False
		ssl_context.verify_mode = ssl.CERT_NONE
		client = Elasticsearch(config['SYSTEM']['elksg'], ssl_context=ssl_context, timeout=60, http_auth=(config['SYSTEM']['elksguser'], config['SYSTEM']['elksgpass']))
	except:
		sys.exit()
else:
	client = Elasticsearch(config['SYSTEM']['elksg'])

squish2.perflog(client, "system", "some random stuff goes here")
