#!/usr/bin/python
# twitter account dispatcher
import csv, json, os, random, re, sys, time, hashlib
import redis
from walrus import *

wal = Walrus(host='localhost', port=6379, db=0)
qq = wal.Set("work")

accts = open(sys.argv[1], 'r')

for acct in accts:
	acct = str(acct.rstrip())
	qq.add(acct)
