#!/usr/bin/python
#DESC: Rate limit checker.
import tweepy
import os, sys
import configparser

if len(sys.argv) == 1:
    myconf = os.environ['HOME'] +'/.twitter'
if len(sys.argv) == 2:
    myconf = sys.argv[1]

config = configparser.ConfigParser()
config.read(myconf)

auth = tweepy.OAuthHandler(config['API']['consumer_key'], config['API']['consumer_secret'])
auth.set_access_token(config['API']['access_token_key'], config['API']['access_token_secret'])
api = tweepy.API(auth)

zod = api.rate_limit_status()
for zoop in zod['resources']:
	for zord in zod['resources'][zoop]:
		#if(zod['resources'][zoop][zord]['remaining'] < zod['resources'][zoop][zord]['limit']):
			print(zoop)
			print(zord)
			print(zord + " " + str(zod['resources'][zoop][zord]['remaining']) + "/" +str(zod['resources'][zoop][zord]['limit']))

