#!/usr/bin/python
import tweepy, csv, sys, os
from simpleconfigparser import simpleconfigparser

config = simpleconfigparser()
config.read(os.environ['HOME'] +'/.twitter')

auth = tweepy.OAuthHandler(config.API.consumer_key, config.API.consumer_secret)
auth.set_access_token(config.API.access_token_key, config.API.access_token_secret)
api = tweepy.API(auth)


#nope
#api.update_status(sys.argv[1],sys.argv[2])

api.update_status(sys.argv[1],int(sys.argv[2]))


