#!/usr/bin/python
import getpass
from walrus import *

wal = Walrus(host='localhost', port=6379, db=0)
adds = wal.Set(getpass.getuser() + "adds")
work = wal.Set(getpass.getuser() + "work")
seen = wal.Set(getpass.getuser() + "seen")
print(adds)
print(seen)
print(work)
