#!/usr/bin/python
import getpass, sys, time, os
from walrus import *
import configparser

config = configparser.ConfigParser()
config.read(os.environ['HOME'] +'/.twitter')



wal = Walrus(host=config['STREAM']['redishost'],port=config['STREAM']['redisport'], db=0)
tum = wal.Set("usertest")
tot = len(tum)
print(tot)
