#!/usr/bin/python
import getpass, sys, os, configparser
from walrus import *

config = configparser.ConfigParser()
config.read(os.environ['HOME'] +'/.twitter')

if len(sys.argv) == 1:
	name = getpass.getuser()
if len(sys.argv) == 2:
    name = sys.argv[1]


wal = Walrus(host=config['STREAM']['redishost'],port=config['STREAM']['redisport'], db=0)
adds = wal.Set(name + "adds")
work = wal.Set(name + "work")
seen = wal.Set(name + "seen")
print(adds)
print(seen)
print(work)
