#!/usr/bin/python
import getpass, sys, time
from walrus import *

incr = 60
if len(sys.argv) == 2:
	incr = int(sys.argv[1])

wal = Walrus(host='localhost', port=6379, db=0)
tum = wal.Set("usertest")

while True:
	tot = len(tum)
	print(tot)
	time.sleep(incr)
