#!/usr/bin/python
import tweepy, csv, sys, os, re
from simpleconfigparser import simpleconfigparser
from time import gmtime, strftime

config = simpleconfigparser()
config.read(os.environ['HOME'] +'/.twitter')

auth = tweepy.OAuthHandler(config.API.consumer_key, config.API.consumer_secret)
auth.set_access_token(config.API.access_token_key, config.API.access_token_secret)
api = tweepy.API(auth)

y = api.verify_credentials()

name = y.screen_name

lists = api.lists_all(name)
for list in lists:
   # check re for ^trm
   print list.slug
   if re.match("trm-", list.slug):

      #make directory if its brand new list
      dirname = list.slug[4:]
      dirname = dirname.replace('-', '') 
      if not os.path.isdir(dirname):
         os.makedirs(dirname)

      #capture list description, helps tech support if they're
      #in shell digging for stuff
      desc = open("./" + dirname + "/description.txt", 'w')
      desc.write(list.description + "\n")
      desc.close()
      names = open("./" + dirname + "/names.txt", 'w')

      #process list
      for member in tweepy.Cursor(api.list_members,name,list.slug).items():
          #record sighting. this needs pruning, how to keep first & last?
          names = open("./" + dirname + "/names.txt", 'a')
          names.write(member.screen_name + "\n")
          focnt = str(member.followers_count)
          frcnt = str(member.friends_count)
          statc = str(member.statuses_count)
          members = open("./" + dirname + "/memberlog.csv", 'a')
          members.write(strftime("%Y-%m-%d %H:%M:%S", gmtime()) + "," + y.screen_name + "," + list.slug[4:] + "," + member.screen_name + ","  + member.id_str + ","  + str(member.created_at) + "," + frcnt + "," + focnt + "," + statc  + "\n")
          print(strftime("%Y-%m-%d %H:%M:%S", gmtime()) + ","  + y.screen_name + "," + list.slug[4:] + "," +member.screen_name + ","  + member.id_str + ","  + str(member.created_at) + "," + frcnt + "," + focnt + "," + statc  + "\n")
          members.close()
          print(member.screen_name + " added to memberlog.csv\n")
          #detected idled & never processed file - user has always been locked
          if os.path.isfile( "./" + dirname + "/idle-" + member.screen_name  + "-consolidated-1970-01-01-00-00.txt") or os.path.isfile( "./" + dirname + "/idle-" + member.screen_name):
              #
              print "Already tracking " + member.screen_name + "\n"

          #the final act, it's not found
          elif not os.path.isfile( "./" + dirname + "/" + member.screen_name):
              #this is first appearance
              firsttime = open("./" + dirname + "/firsttime.csv", 'a')
              firsttime.write(strftime("%Y-%m-%d %H:%M:%S", gmtime()) + ","  + y.screen_name + "," + list.slug[4:] + "," + member.screen_name + ","  + member.id_str + ","  + str(member.created_at) + "," + frcnt + "," + focnt + "," + statc  + "\n")
              firsttime.close()
              print(member.screen_name + " appended to first time file\n")
              new = open("./" + dirname + "/" + member.screen_name + "-consolidated-1970-01-01-00-00.txt", 'w') 
              new.write("999999999999999999")
              new.close()
              #sense prior activity with time stamp free file in account's name
              new = open("./" + dirname + "/" + member.screen_name, 'w')
              new.close()
