#!/usr/bin/python
import csv, json, os, random, re, sys, time, redis, tweepy, getpass
import configparser
from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search
import ssl
from elasticsearch.connection import create_ssl_context

try:
        ssl_context = create_ssl_context(cafile='/home/root-ca.pem')
        ssl_context.check_hostname = False
        ssl_context.verify_mode = ssl.CERT_NONE

        client = Elasticsearch('https://hp0.netwarsystem.com:9200', ssl_context=ssl_context, timeout=60, http_auth=("admin", "LongPassword2019"))
except:
        sys.exit()

accts = open(sys.argv[1], 'r')
for acct in accts:
	acct = acct.rstrip()
	s = Search(using=client, index="tumaster").query("match", _id=acct)
	response = s.execute()
	if(response):
		#print("found " + str(acct))
		k = 0
	else:
		print(acct)
