#!/usr/bin/python
#DESC: Any list that begins with trm- is treated as a list of accounts
#DESC: to record. List names are used as subdirectories. The net effect
#DESC: of this script is a batch application of tw-prime to a list.
#DESC: This just writes 1970 'primer' files, which get processed
#DESC: by the normal execution of N-queue.
import tweepy, csv, sys, os, re
import configparser
from time import gmtime, strftime

config = configparser()
config.read(os.environ['HOME'] +'/.twitter')


auth = tweepy.OAuthHandler(config[API][consumer_key], config[API][consumer_secret])
auth.set_access_token(config[API][access_token_key], config[API][access_token_secret])
api = tweepy.API(auth)

y = api.verify_credentials()

name = y.screen_name

lists = api.lists_all(name)
for list in lists:
   # check re for ^trm
   print list.slug
   if re.match("trm-", list.slug):

      #make directory if its brand new list
      dirname = list.slug[4:]
      dirname = dirname.replace('-', '') 
      if not os.path.isdir(dirname):
         os.makedirs(dirname)

      #capture list description, helps tech support if they're
      #in shell digging for stuff
      desc = open("./" + dirname + "/description.txt", 'w')
      desc.write(list.description + "\n")
      desc.close()

      #process list
      for member in tweepy.Cursor(api.list_members,name,list.slug).items():
          #record sighting. this needs pruning, how to keep first & last?
          focnt = str(member.followers_count)
          frcnt = str(member.friends_count)
          statc = str(member.statuses_count)
          members = open("./" + dirname + "/memberlog.csv", 'a')
          members.write(member.screen_name + ","  + member.id_str + "," + strftime("%Y-%m-%d %H:%M:%S", gmtime()) + "," + str(member.created_at) + "," + frcnt + "," + focnt + "," + statc  + "\n")
          print(member.screen_name + ","  + member.id_str + "," + strftime("%Y-%m-%d %H:%M:%S", gmtime()) + "," + str(member.created_at) + "," + frcnt + "," + focnt + "," + statc  + "\n")
          members.close()
          #detected idled & never processed file - user has always been locked
          if os.path.isfile( "./" + dirname + "/idle-" + member.screen_name  + "-consolidated-1970-01-01-00-00.txt") or os.path.isfile( "./" + dirname + "/idle-" + member.screen_name):
              #
              print "Already tracking " + member.screen_name + "\n"

          #the final act, it's not found
          elif not os.path.isfile( "./" + dirname + "/" + member.screen_name):
              #this is first appearance
              firsttime = open("./" + dirname + "/firsttime.csv", 'a')
              firsttime.write(member.screen_name + ","  + member.id_str + "," + strftime("%Y-%m-%d %H:%M:%S", gmtime()) + "," + str(member.created_at) + "," + frcnt + "," + focnt + "," + statc  + "\n")
              firsttime.close()
              new = open("./" + dirname + "/" + member.screen_name + "-consolidated-1970-01-01-00-00.txt", 'w') 
              new.write("999999999999999999")
              new.close()
