#!/usr/bin/python
import csv, json, os, random, re, sys, time, redis, tweepy, getpass
import configparser
from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search
import ssl
from elasticsearch.connection import create_ssl_context

try:
        ssl_context = create_ssl_context(cafile='/home/root-ca.pem')
        ssl_context.check_hostname = False
        ssl_context.verify_mode = ssl.CERT_NONE

        client = Elasticsearch('https://hp1.netwarsystem.com:9200', ssl_context=ssl_context, timeout=60, http_auth=("admin", "LongPassword2019"))
except:
        sys.exit()

accts = open(sys.argv[1], 'r')
for acct in accts:
	acct = acct.rstrip()
	s = Search(using=client, index="userids").query("match",screen_name=acct)
	response = s.execute()
	if(response):
		for resp in response:
#			print(resp)
#			print(dir(resp))
        		print(resp['id_str'])
#        		print(resp.text)

	else:
		k=0

#<Hit(tumaster/twid/420217887): {'id': 420217887, 'id_str': '420217887', 'name': 'Ayub Khali...}>
#['contributors_enabled',
# 'created_at',
# 'default_profile',
# 'default_profile_image',
# 'description',
# 'entities',
# 'favourites_count',
# 'follow_request_sent',
# 'followers_count',
# 'following',
# 'friends_count',
# 'geo_enabled',
# 'has_extended_profile',
# 'id',
# 'id_str',
# 'is_translation_enabled',
# 'is_translator',
# 'lang',
# 'listed_count',
# 'location',
# 'meta',
# 'name',
# 'notifications',
# 'profile_background_color',
# 'profile_background_image_url',
# 'profile_background_image_url_https',
# 'profile_background_tile',
# 'profile_banner_url',
# 'profile_image_url',
# 'profile_image_url_https',
# 'profile_link_color',
# 'profile_location',
# 'profile_sidebar_border_color',
# 'profile_sidebar_fill_color',
# 'profile_text_color',
# 'profile_use_background_image',
# 'protected',
# 'screen_name',
# 'status',
# 'statuses_count',
# 'time_zone',
# 'translator_type',
# 'url',
# 'utc_offset',
# 'verified']
#
