#!/usr/bin/python
#DESC: Rate limit checker.
import tweepy
import os
import configparser

config = configparser()
config.read(os.environ['HOME'] +'/.twitter')


auth = tweepy.OAuthHandler(config[API][consumer_key], config[API][consumer_secret])
auth.set_access_token(config[API][access_token_key], config[API][access_token_secret])
api = tweepy.API(auth)

rlim = api.rate_limit_status()[u'resources'][u'users'][u'/users/lookup'][u'remaining']
print rlim

rlim = api.rate_limit_status()[u'resources'][u'users'][u'/users/search'][u'remaining']
print rlim

rlim = api.rate_limit_status()[u'resources'][u'users'][u'/users/show'][u'remaining']
print rlim

#GET users/lookup	users	900	300
#GET users/search	users	900	0
#GET users/show
