#!/usr/bin/python
# one shot bulk Twitter account recorder
import csv, json, os, random, re, sys, time, datetime
import urllib2, redis, tweepy
from simpleconfigparser import simpleconfigparser
from elasticsearch import Elasticsearch
#from elasticsearch_dsl import Search
from walrus import *

# main begin
config = simpleconfigparser()
config.read(os.environ['HOME'] +'/.twitter')

try:
	client = Elasticsearch(use_ssl=True, verify_certs=False, http_auth="admin:admin")
except:
	print("no client")
	sys.exit()

auth = tweepy.OAuthHandler(config.API.consumer_key, config.API.consumer_secret)
auth.set_access_token(config.API.access_token_key, config.API.access_token_secret)
api = tweepy.API(auth)
my = api.verify_credentials()

try:
	z = api.get_user(sys.argv[1])
	if z:
		bod = "{ \"index\" : { \"_index\" : \"twusers\", \"_type\" : \"twuser\" } }\n"
		bod = bod + json.dumps(z._json) + "\n"
		k = client.bulk(index="twusers",doc_type="twuser",body=bod)
except (RuntimeError, TypeError, NameError):
		pass

