#!/usr/bin/python
#DESC: Rate limit checker.
import tweepy
import os
import configparser

config = configparser.ConfigParser()
config.read(os.environ['HOME'] +'/.twitter')


auth = tweepy.OAuthHandler(config['API']['consumer_key'], config['API']['consumer_secret'])
auth.set_access_token(config['API']['access_token_key'], config['API']['access_token_secret'])
api = tweepy.API(auth)

zod = api.rate_limit_status()
for zoop in zod['resources']:
	for zord in zod['resources'][zoop]:
		if(zod['resources'][zoop][zord]['remaining'] < zod['resources'][zoop][zord]['limit']):
			print(zord + " " + str(zod['resources'][zoop][zord]['remaining']) + "/" +str(zod['resources'][zoop][zord]['limit']))

