#!/usr/bin/python
#DESC: Rate limit checker.
import tweepy
import os
import configparser

config = configparser.ConfigParser()
config.read(os.environ['HOME'] +'/.twitter')


auth = tweepy.OAuthHandler(config['API']['consumer_key'], config['API']['consumer_secret'])
auth.set_access_token(config['API']['access_token_key'], config['API']['access_token_secret'])
api = tweepy.API(auth)

zod = api.rate_limit_status()
for zoop in zod['resources']:
	for zord in zod['resources'][zoop]:
		if(zod['resources'][zoop][zord]['remaining'] < zod['resources'][zoop][zord]['limit']):
			print(zord + " " + str(zod['resources'][zoop][zord]['remaining']) + "/" +str(zod['resources'][zoop][zord]['limit']))

#{'lists': {'/lists/list': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
# '/lists/memberships': {'limit': 75, 'remaining': 75, 'reset': 1549697590},
# '/lists/subscribers/show': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
# '/lists/members': {'limit': 900, 'remaining': 900, 'reset': 1549697590},
# '/lists/subscriptions': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
# '/lists/show': {'limit': 75, 'remaining': 75, 'reset': 1549697590},
# '/lists/ownerships': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
# '/lists/subscribers': {'limit': 180, 'remaining': 180, 'reset': 1549697590},
# '/lists/members/show': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
# '/lists/statuses': {'limit': 900, 'remaining': 900, 'reset': 1549697590}},
#lists
#/lists/list
#/lists/memberships
#/lists/subscribers/show
#/lists/members
#/lists/subscriptions
#/lists/show
#/lists/ownerships
#/lists/subscribers
#/lists/members/show
#/lists/statuses
#lists
#/lists/list
#{'limit': 15, 'remaining': 15, 'reset': 1549698293}
#/lists/memberships
#{'limit': 75, 'remaining': 75, 'reset': 1549698293}
#/lists/subscribers/show
#{'limit': 15, 'remaining': 15, 'reset': 1549698293}
#/lists/members
#{'limit': 900, 'remaining': 900, 'reset': 1549698293}
#/lists/subscriptions
#{'limit': 15, 'remaining': 15, 'reset': 1549698293}
#/lists/show
#{'limit': 75, 'remaining': 75, 'reset': 1549698293}
#/lists/ownerships
#{'limit': 15, 'remaining': 15, 'reset': 1549698293}
#/lists/subscribers
#{'limit': 180, 'remaining': 180, 'reset': 1549698293}
#/lists/members/show
#{'limit': 15, 'remaining': 15, 'reset': 1549698293}
#/lists/statuses
#{'limit': 900, 'remaining': 900, 'reset': 1549698293}
#
#
## 'application': {'/application/rate_limit_status': {'limit': 180, 'remaining': 179, 'reset': 1549697590}},
## 'mutes': {'/mutes/users/list': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/mutes/users/ids': {'limit': 15, 'remaining': 15, 'reset': 1549697590}},
## 'live_video_stream': {'/live_video_stream/status/:id': {'limit': 1000, 'remaining': 1000, 'reset': 1549697590}},
## 'friendships': {'/friendships/outgoing': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/friendships/list': {'limit': 200, 'remaining': 200, 'reset': 1549697590},
## '/friendships/no_retweets/ids': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/friendships/lookup': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/friendships/incoming': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/friendships/show': {'limit': 180, 'remaining': 180, 'reset': 1549697590}},
## 'guide': {'/guide': {'limit': 180, 'remaining': 180, 'reset': 1549697590}},
## 'auth': {'/auth/csrf_token': {'limit': 15, 'remaining': 15, 'reset': 1549697590}},
## 'blocks': {'/blocks/list': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/blocks/ids': {'limit': 15, 'remaining': 15, 'reset': 1549697590}},
## 'geo': {'/geo/similar_places': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/geo/id/:place_id': {'limit': 75, 'remaining': 75, 'reset': 1549697590},
## '/geo/reverse_geocode': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/geo/search': {'limit': 15, 'remaining': 15, 'reset': 1549697590}},
## 'users': {'/users/report_spam': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/users/contributors/pending': {'limit': 2000, 'remaining': 2000, 'reset': 1549697590},
## '/users/show/:id': {'limit': 900, 'remaining': 900, 'reset': 1549697590},
## '/users/search': {'limit': 900, 'remaining': 900, 'reset': 1549697590},
## '/users/suggestions/:slug': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/users/contributees/pending': {'limit': 200, 'remaining': 200, 'reset': 1549697590},
## '/users/derived_info': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/users/profile_banner': {'limit': 180, 'remaining': 180, 'reset': 1549697590},
## '/users/suggestions/:slug/members': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/users/lookup': {'limit': 900, 'remaining': 900, 'reset': 1549697590},
## '/users/suggestions': {'limit': 15, 'remaining': 15, 'reset': 1549697590}},
## 'followers': {'/followers/ids': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/followers/list': {'limit': 15, 'remaining': 15, 'reset': 1549697590}},
## 'collections': {'/collections/list': {'limit': 1000, 'remaining': 1000, 'reset': 1549697590},
## '/collections/entries': {'limit': 1000, 'remaining': 1000, 'reset': 1549697590},
## '/collections/show': {'limit': 1000, 'remaining': 1000, 'reset': 1549697590}},
## 'statuses': {'/statuses/retweeters/ids': {'limit': 75, 'remaining': 75, 'reset': 1549697590},
## '/statuses/retweets_of_me': {'limit': 75, 'remaining': 75, 'reset': 1549697590},
## '/statuses/home_timeline': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/statuses/show/:id': {'limit': 900, 'remaining': 900, 'reset': 1549697590},
## '/statuses/user_timeline': {'limit': 900, 'remaining': 900, 'reset': 1549697590},
## '/statuses/friends': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/statuses/retweets/:id': {'limit': 75, 'remaining': 75, 'reset': 1549697590},
## '/statuses/mentions_timeline': {'limit': 75, 'remaining': 75, 'reset': 1549697590},
## '/statuses/oembed': {'limit': 180, 'remaining': 180, 'reset': 1549697590},
## '/statuses/lookup': {'limit': 900, 'remaining': 900, 'reset': 1549697590}},
## 'custom_profiles': {'/custom_profiles/list': {'limit': 180, 'remaining': 180, 'reset': 1549697590},
## '/custom_profiles/show': {'limit': 180, 'remaining': 180, 'reset': 1549697590}},
## 'webhooks': {'/webhooks/subscriptions/direct_messages': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/webhooks': {'limit': 15, 'remaining': 15, 'reset': 1549697590}},
## 'contacts': {'/contacts/uploaded_by': {'limit': 300, 'remaining': 300, 'reset': 1549697590},
## '/contacts/users': {'limit': 300, 'remaining': 300, 'reset': 1549697590},
## '/contacts/addressbook': {'limit': 300, 'remaining': 300, 'reset': 1549697590},
## '/contacts/users_and_uploaded_by': {'limit': 300, 'remaining': 300, 'reset': 1549697590},
## '/contacts/delete/status': {'limit': 300, 'remaining': 300, 'reset': 1549697590}},
## 'i': {'/i/config': {'limit': 15, 'remaining': 15, 'reset': 1549697590}},
## 'tweet_prompts': {'/tweet_prompts/report_interaction': {'limit': 180, 'remaining': 180, 'reset': 1549697590},
## '/tweet_prompts/show': {'limit': 180, 'remaining': 180, 'reset': 1549697590}},
## 'moments': {'/moments/statuses/update': {'limit': 5, 'remaining': 5, 'reset': 1549697590},
## '/moments/permissions': {'limit': 300, 'remaining': 300, 'reset': 1549697590}},
## 'help': {'/help/tos': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/help/configuration': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/help/privacy': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/help/settings': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/help/languages': {'limit': 15, 'remaining': 15, 'reset': 1549697590}},
## 'feedback': {'/feedback/show/:id': {'limit': 180, 'remaining': 180, 'reset': 1549697590},
## '/feedback/events': {'limit': 1000, 'remaining': 1000, 'reset': 1549697590}},
## 'business_experience': {'/business_experience/dashboard_settings/destroy': {'limit': 450, 'remaining': 450, 'reset': 1549697590},
## '/business_experience/dashboard_features': {'limit': 450, 'remaining': 450, 'reset': 1549697590},
## '/business_experience/keywords': {'limit': 450, 'remaining': 450, 'reset': 1549697590},
## '/business_experience/dashboard_settings/update': {'limit': 450, 'remaining': 450, 'reset': 1549697590},
## '/business_experience/dashboard_settings/show': {'limit': 450, 'remaining': 450, 'reset': 1549697590}},
## 'graphql&POST': {'/graphql&POST': {'limit': 2500, 'remaining': 2500, 'reset': 1549697590}},
## 'friends': {'/friends/following/ids': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/friends/following/list': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/friends/list': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/friends/ids': {'limit': 15, 'remaining': 15, 'reset': 1549697590}},
## 'sandbox': {'/sandbox/account_activity/webhooks/:id/subscriptions': {'limit': 500, 'remaining': 500, 'reset': 1549697590}},
## 'drafts': {'/drafts/statuses/update': {'limit': 450, 'remaining': 450, 'reset': 1549697590},
## '/drafts/statuses/destroy': {'limit': 450, 'remaining': 450, 'reset': 1549697590},
## '/drafts/statuses/ids': {'limit': 450, 'remaining': 450, 'reset': 1549697590},
## '/drafts/statuses/list': {'limit': 450, 'remaining': 450, 'reset': 1549697590},
## '/drafts/statuses/show': {'limit': 450, 'remaining': 450, 'reset': 1549697590},
## '/drafts/statuses/create': {'limit': 450, 'remaining': 450, 'reset': 1549697590}},
## 'direct_messages': {'/direct_messages/sent': {'limit': 300, 'remaining': 300, 'reset': 1549697590},
## '/direct_messages/broadcasts/list': {'limit': 60, 'remaining': 60, 'reset': 1549697590},
## '/direct_messages/subscribers/lists/members/show': {'limit': 1000, 'remaining': 1000, 'reset': 1549697590},
## '/direct_messages/mark_read': {'limit': 1000, 'remaining': 1000, 'reset': 1549697590},
## '/direct_messages/subscribers/ids': {'limit': 180, 'remaining': 180, 'reset': 1549697590},
## '/direct_messages/sent_and_received': {'limit': 300, 'remaining': 300, 'reset': 1549697590},
## '/direct_messages/broadcasts/statuses/list': {'limit': 60, 'remaining': 60, 'reset': 1549697590},
## '/direct_messages': {'limit': 300, 'remaining': 300, 'reset': 1549697590},
## '/direct_messages/subscribers/lists/members/ids': {'limit': 180, 'remaining': 180, 'reset': 1549697590},
## '/direct_messages/subscribers/show': {'limit': 180, 'remaining': 180, 'reset': 1549697590},
## '/direct_messages/broadcasts/show': {'limit': 60, 'remaining': 60, 'reset': 1549697590},
## '/direct_messages/broadcasts/statuses/show': {'limit': 60, 'remaining': 60, 'reset': 1549697590},
## '/direct_messages/subscribers/lists/list': {'limit': 180, 'remaining': 180, 'reset': 1549697590},
## '/direct_messages/show': {'limit': 300, 'remaining': 300, 'reset': 1549697590},
## '/direct_messages/events/list': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/direct_messages/subscribers/lists/show': {'limit': 180, 'remaining': 180, 'reset': 1549697590},
## '/direct_messages/events/show': {'limit': 15, 'remaining': 15, 'reset': 1549697590}},
## 'media': {'/media/upload': {'limit': 500, 'remaining': 500, 'reset': 1549697590}},
## 'traffic': {'/traffic/map': {'limit': 15, 'remaining': 15, 'reset': 1549697590}},
## 'account_activity': {'/account_activity/all/webhooks': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/account_activity/all/:instance_name/subscriptions': {'limit': 500, 'remaining': 500, 'reset': 1549697590},
## '/account_activity/direct_messages/webhooks': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/account_activity/webhooks/:id/subscriptions/direct_messages/list': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/account_activity/webhooks/:id/subscriptions/all': {'limit': 500, 'remaining': 500, 'reset': 1549697590},
## '/account_activity/direct_messages/:instance_name/webhooks': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/account_activity/webhooks/:id/subscriptions/all/list': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/account_activity/webhooks/:id/subscriptions/direct_messages': {'limit': 500, 'remaining': 500, 'reset': 1549697590},
## '/account_activity/webhooks': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/account_activity/direct_messages/:instance_name/subscriptions': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/account_activity/webhooks/:id/subscriptions': {'limit': 500, 'remaining': 500, 'reset': 1549697590},
## '/account_activity/all/:instance_name/webhooks': {'limit': 15, 'remaining': 15, 'reset': 1549697590}},
## 'account': {'/account/login_verification_enrollment': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/account/update_profile': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/account/verify_credentials': {'limit': 75, 'remaining': 75, 'reset': 1549697590},
## '/account/settings': {'limit': 15, 'remaining': 15, 'reset': 1549697590}},
## 'safety': {'/safety/detection_feedback': {'limit': 1000, 'remaining': 1000, 'reset': 1549697590}},
## 'favorites': {'/favorites/list': {'limit': 75, 'remaining': 75, 'reset': 1549697590}},
## 'device': {'/device/token': {'limit': 15, 'remaining': 15, 'reset': 1549697590}},
## 'tweets': {'/tweets/stream/filter/rules': {'limit': 450, 'remaining': 450, 'reset': 1549697590},
## '/tweets/stream/filter/:instance_name': {'limit': 50, 'remaining': 50, 'reset': 1549697590},
## '/tweets/search/:product/:label': {'limit': 1800, 'remaining': 1800, 'reset': 1549697590},
## '/tweets/search/:product/:instance/counts': {'limit': 900, 'remaining': 900, 'reset': 1549697590},
## '/tweets/stream/filter/rules/:instance_name/validation&POST': {'limit': 450, 'remaining': 450, 'reset': 1549697590},
## '/tweets/stream/filter/rules/:instance_name&POST': {'limit': 450, 'remaining': 450, 'reset': 1549697590},
## '/tweets/stream/filter/rules/:instance_name&DELETE': {'limit': 450, 'remaining': 450, 'reset': 1549697590},
## '/tweets/stream/filter/rules/:instance_name/:rule_id': {'limit': 450, 'remaining': 450, 'reset': 1549697590}},
## 'saved_searches': {'/saved_searches/destroy/:id': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/saved_searches/show/:id': {'limit': 15, 'remaining': 15, 'reset': 1549697590},
## '/saved_searches/list': {'limit': 15, 'remaining': 15, 'reset': 1549697590}},
## 'oauth': {'/oauth/invalidate_token': {'limit': 450, 'remaining': 450, 'reset': 1549697590}},
## 'search': {'/search/tweets': {'limit': 180, 'remaining': 180, 'reset': 1549697590}},
## 'trends': {'/trends/closest': {'limit': 75, 'remaining': 75, 'reset': 1549697590},
## '/trends/available': {'limit': 75, 'remaining': 75, 'reset': 1549697590},
## '/trends/place': {'limit': 75, 'remaining': 75, 'reset': 1549697590}},
## 'live_pipeline': {'/live_pipeline/events': {'limit': 180, 'remaining': 180, 'reset': 1549697590}}}
#
##lists
##application
##mutes
##live_video_stream
##friendships
##guide
##auth
##blocks
##geo
##users
##followers
##collections
##statuses
##custom_profiles
##webhooks
##contacts
##i
##tweet_prompts
##moments
##help
##feedback
##business_experience
##graphql&POST
##friends
##sandbox
##drafts
##direct_messages
##media
##traffic
##account_activity
##account
##safety
##favorites
##device
##tweets
##saved_searches
##oauth
##search
##trends
##live_pipeline
##
