#!/usr/bin/python
import getpass, sys, os, configparser
from walrus import *

config = configparser.ConfigParser()
config.read(os.environ['HOME'] +'/.twitter')



wal = Walrus(host=config['SYSTEM']['redishost'],port=config['SYSTEM']['redisport'], db=0)
tum = wal.Set(sys.argv[1].rstrip())
print(tum)
