#!/usr/bin/python
import getpass, sys, os, configparser
from walrus import *

sysconf = configparser.ConfigParser()
sysconf.read('/etc/netwar/netwar.conf')

if(len(sys.argv) < 2):
	sys.exit()


wal = Walrus(host=sysconf['SYSTEM']['redishost'],port=sysconf['SYSTEM']['redisport'], db=0)
tum = wal.Set(sys.argv[1].rstrip())
print(tum)
