#!/usr/bin/python
# twitter account dispatcher
import csv, json, os, random, re, sys, time, hashlib
import redis, configparser
from walrus import *

sysconf = configparser.ConfigParser()
sysconf.read('/etc/netwar/netwar.conf')


wal = Walrus(host=sysconf['SYSTEM']['redishost'],port=config['SYSTEM']['redisport'], db=0)
qq = wal.Set(sys.argv[1])
qq.clear()
