#!/usr/bin/python
# load numeric IDs to a Walrus work queue
import redis, configparser, sys
from walrus import *

sysconf = configparser.ConfigParser()
sysconf.read('/etc/netwar/netwar.conf')


wal = Walrus(host=sysconf['SYSTEM']['redishost'],port=sysconf['SYSTEM']['redisport'], db=0)
qq = wal.Set(sys.argv[1])

accts = open(sys.argv[2], 'r')

for acct in accts:
	acct = str(acct.rstrip())
	qq.add(acct)
