#!/usr/bin/python
# twitter account dispatcher
import csv, json, os, random, re, sys, time, hashlib
import redis, configparser
from walrus import *

config = configparser.ConfigParser()
config.read(os.environ['HOME'] +'/.twitter')


wal = Walrus(host=config['SYSTEM']['redishost'],port=config['SYSTEM']['redisport'], db=0)
qq = wal.Set("batch")
qq.clear()
