#!/usr/bin/python
import getpass, configparser
from walrus import *

sysconf = configparser.ConfigParser()
sysconf.read('/etc/netwar/netwar.conf')

wal = Walrus(host=sysconf['SYSTEM']['redishost'],port=config['SYSTEM']['redisport'], db=0)
adds = wal.Set(getpass.getuser() + "adds")
work = wal.Set(getpass.getuser() + "work")
seen = wal.Set(getpass.getuser() + "seen")
adds.clear()
seen.clear()
work.clear()
